language: python
python:
  - 3.5

# Setup anaconda
install:
  - sudo apt-get install libhdf5-serial-dev
  - sudo apt-get install gfortran
  - sudo apt-get install gcc
  - sudo apt-get install build-essential
  - sudo apt-get install cmake
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install git
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda install -c anaconda h5py
  - conda install -c conda-forge pyne
  - conda install -c anaconda pytest

# run
script:
  - pytest saltproc
