dependencies:
  - pyne
  - numpy
  - scipy
  - pytables
  - networkx
  - pydotplus
  - pytest
  - sphinx
  - sphinx_rtd_theme
  - argparse
  - tomli
  - py
  - pluggy
  - packaging
  - iniconfig
  - attrs
  - pyparsing
