name: saltproc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - openmc
  - pytables
  - networkx
  - pydot
  - pytest
  - jsonschema
  - pip:
    - serpentTools
    - argparse==1.4.0
