name: saltproc-doc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - openmc
  - pytables
  - networkx
  - pydot
  - jsonschema
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - serpentTools
    - sphinx-multiversion
    - sphinxcontrib-apidoc
    - sphinx-jsonschema
