name: saltproc-doc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pyne>=0.5.11
  - numpy>=1.14.0
  - pytables
  - networkx
  - pydotplus
  - pytest
  - sphinx
  - sphinx-intl
  - sphinx_rtd_theme
  - gitpython
  - rsync
  - pip:
      - pystemmer
      - rinohtype
