name: saltproc-doc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pyne>=0.5.11
  - numpy>=1.14.0
  - pytables
  - sphinx
  - sphinx_rtd_theme
  - pip:
      - sphinx-multiversion
      - sphinxcontrib-apidoc
