# Preamble
name: Cache dependencies (conda-v-2)

on:
  push:
    branches:
      - ci-testing
  #  schedule:
  #    - cron: '0 9 * * 1' # run every monday @ 9AM

jobs:
  cache-dependencies-conda:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
# Check for existing cache
      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Find existing cache
        id: conda-cache
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: |
            ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda2-$${ hashFiles('envrionment.yml')-${{ env.DATE }}-${{ env.CACHE_NUMBER }} }
          restore-keys: |
            ${{ runner.os }}-conda2-

# Setup python
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: saltproc-env
          use-mamba: true
          use-only-tar-bz2: true

# Install dependencies
      - name: Install dependencies and SaltProc
        if: steps.conda-cache.outputs.cache-hit != 'true'
        run: mamba install --file conda-dependencies.txt
