# Preamble
name: Cache dependencies (combined-1)

on:
  push:
    branches:
      - ci-testing
  #  schedule:
  #    - cron: '0 9 * * 1' # run every monday @ 9AM

jobs:
  cache-dependencies-combined:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


# Check for existing cache
      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        id: combined-cache
        env:
          CACHE_NUMBER: 3
        with:
          path: |
            /usr/share/miniconda3/envs/saltproc-env
            ~/conda_pkgs_dir
            ~/.cache/pip
          key: ${{ runner.os }}-combined1-$${ hashFiles('environment.yml')-${{ env.DATE }}-${{ env.CACHE_NUMBER }} }

# Setup conda 
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: saltproc-env
          use-mamba: true
          use-only-tar-bz2: true
      - run: |
          conda config --env --set pip_interop_enabled True

# Install dependencies
      - name: Update environment
        run: mamba env update -n saltproc-env -f environment.yml
        if: steps.combined-cache.outputs.cache-hit != 'true'

      - name: Check packages
        run: conda list

      - name: Install SaltProc
        run: |
          conda activate saltproc-env
          python setup.py install
