# Preamble
name: Deploy SaltProc docs

on:
  push:
    branches:
      - ci-testing
     # - master 
  #workflow_run:
    #workflows: "Test SaltProc"
    #branches: [master]
    #types:
    #  - completed


env:
  CACHE_NUMBER: 0 #change to manually reset cache

jobs:
  call-cache-dependencies:
    uses: yardasol/saltproc/.github/workflows/cache-dependencies.yml@ci-testing
    #uses: arfc/saltproc/.github/workflows/cache-dependencies.yml@master
    
  deploy-docs:
    runs-on: ubuntu-latest
      #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Build Sphinx Documentation
        run: |
          cd doc
          sphinx-apidoc --separate --force --output-dir=src/ ../saltproc
          make clean
          make html

      - name: Deploy documentation to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/_build/html
