# Preamble
name: Deploy SaltProc docs

on:
  push:
    branches:
      - master 

env:
  CACHE_NUMBER: 0 #change to manually reset cache

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
      #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

# Setup conda 
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: saltproc-env
          use-mamba: true
          use-only-tar-bz2: true
      - run: |
          conda config --env --set pip_interop_enabled True

# check for existing cache
      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        id: dependencies-cache
        with:
          path: |
            /usr/share/miniconda3/envs/saltproc-env
            ~/.cache/pip
          key: depcache-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}

# Install dependencies
      - name: Update environment
        run: mamba env update -n saltproc-env -f environment.yml
        if: steps.dependencies-cache.outputs.cache-hit != 'true'

      - name: Install SaltProc
        run:  python setup.py install

      - name: Check packages
        run: conda list

      - name: Build Sphinx Documentation
        run: |
          cd doc
          sphinx-apidoc --separate --force --output-dir=src/ ../saltproc
          make clean
          make html

      - name: Deploy documentation to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/_build/html
