# Preamble
name: Create next minor release 

on:
  release: [publish]
  # enable worflow to be run manually
  workflow_dispatch:

jobs:
  next-relese-minor:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Get most recent release version
        run: |
          echo "RELEASE_VERSION=$(gh api repos/${{ github.repository }}/releases/tags --jq '.[0] | .name')" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment minor version
        run: |
          IFS='.' read -ra arr <<< ${{ env.RELEASE_VERSION }}
          MINOR_VERSION=$((${arr[1]}+1))
          arr[1]=$MINOR_VERSION
          NEW_RELEASE_VERSION="${arr[0]}.${arr[1]}.${arr[2]}"
          echo "NEW_RELEASE_VERSION="$NEW_RELEASE_VERSION >> $GITHUB_ENV

      - name: Create a new release and milestone.
        run: |
          gh api repos/${{ github.repository }}/releases \
          -H "Authorize: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -X POST \
          -F name=${{ env.NEW_RELEASE_VERSION }} \
          -F draft=true \ 
          -F tag_name=${{ env.NEW_RELEASE_VERSION }}
          gh api repos/${{ github.repository }}/milestones \
          -H "Authorize: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -X POST \
          -F title=${{ env.NEW_RELEASE_VERSION }} 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new release notes
        run: |
          cp doc/releasenotes/template.rst doc/releasenotes/${{ env.NEW_RELEASE_VERSION }}.rst
          sed -i "s/vx.x.x/${{ env.NEW_RELEASE_VERSION }}/g" doc/releasenotes/${{ env.NEW_RELEASE_VERSION }}.rst
          git add doc/releasenotes/${{ env.NEW_RELEASE_VERSION }}.rst
          git commit -m "created ${{ env.NEW_RELEASE_VERSION }} release notes"
          git fetch origin
          git push origin master
