on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
      new-release-version:
        required: true
        type: string
      minor-version:
        required: true
        type: string
      milestone-number:
        required: true
        type: string

    secrets:
      token:
        required: true

jobs:
  make-next-version-final-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ inputs.token }}

      - name: "Make changes necessary for publishing ${{ inputs.new-release-version }} in advance"
        run: |
          echo "Update version.py"
          sed -i "s/_version_micro = '*[0-9]*'*/_version_micro = ''/g" saltproc/version.py
          sed -i "s/_version_minor = [0-9]*/_version_minor = ${{ inputs.minor-version }}/g" saltproc/version.py
          sed -i "s/^# _version_extra = 'dev'/_version_extra = 'dev'/g" saltproc/version.py
          sed -i "s/^_version_extra = '0'/# _version_extra = '0'/g" saltproc/version.py
          echo "Create new release notes"
          cp doc/releasenotes/template.rst doc/releasenotes/${{ inputs.new-release-version }}.rst
          sed -i "s/vx.x.x/${{ inputs.new-release-version }}/g" doc/releasenotes/${{ inputs.new-release-version }}.rst
          sed -i "s/${{ inputs.release-version }}/${{ inputs.new-release-version }}\n  ${{ inputs.release-version }}/g" doc/releasenotes/index.rst
          echo "Prepare for full release"
          sed -i "s/\.\. note:: These release notes are currently in production\.//g" doc/releasenotes/${{ inputs.new-release-version }}.rst
          sed -i "s/^_version_extra = 'dev'/# _version_extra = 'dev'/g" saltproc/version.py
          sed -i "s/# _version_extra = '0'/_version_extra = '0'/g" saltproc/version.py

      - name: "Create PR containing changes necessary for publishing ${{ inputs.new-release-version }}"
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ inputs.token }}
          branch: "${{ inputs.new-release-version }}-final"
          delete-branch: true
          commit-message: "final changes before publishing ${{ inputs.new-release-version }}"
          title: "[REQUIRED FOR PUBLISHING] Finishing touches for version ${{ inputs.new-release-version }}"
          body: "This is an automated PR that updates the version number and release notes in preparation for the full release of version ${{ inputs.new-release-version }}. This should be last PR merged before publishing version ${{ inputs.new-release-version }}. Rebasing this PR on top of the most recent commit in `master` is a prequisite of publishing version ${{ inputs.new-release-version }}. We rebase becasue the commits in this PR were created around the same time development on ${{ inputs.new-release-version }} began."
          reviewers: yardasol
          milestone: ${{ inputs.milestone-number }}
          labels: |
            Priority:2-Normal
            Status:1-New
            Type:Style
            Type:Docs
            Difficulty:1-Beginner
            Comp:Build
