on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
      new-release-version:
        required: true
        type: string
      minor-version:
        required: true
        type: string
      milestone-number:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  make-next-version-inital-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.token }}

      - name: "Make initial changes for ${{ inputs.new-release-version }}"
        run: |
          echo "Update version.py"
          sed -i "s/_version_micro = '*[0-9]*'*/_version_micro = ''/g" saltproc/version.py
          sed -i "s/_version_minor = [0-9]*/_version_minor = ${{ inputs.minor-version }}/g" saltproc/version.py
          sed -i "s/^# _version_extra = 'dev'/_version_extra = 'dev'/g" saltproc/version.py
          sed -i "s/^_version_extra = '0'/# _version_extra = '0'/g" saltproc/version.py
          echo "Create new release notes"
          cp doc/releasenotes/template.rst doc/releasenotes/${{ inputs.new-release-version }}.rst
          sed -i "s/vx.x.x/${{ inputs.new-release-version }}/g" doc/releasenotes/${{ inputs.new-release-version }}.rst
          sed -i "s/${{ inputs.release-version }}/${{ inputs.new-release-version }}\n  ${{ inputs.release-version }}/g" doc/releasenotes/index.rst

      - name: "Create PR containing inital changes for ${{ inputs.new-release-version }}" 
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.token }}
          branch: "${{ inputs.new-release-version }}-init"
          delete-branch: true
          commit-message: "inital changes for ${{ inputs.new-release-version }}"
          title: "[INIT] Update `version.py` and create release notes for version ${{ inputs.new-release-version }}"
          body: "This is an automated PR that updates the version number and creates the release notes file for version ${{ inputs.new-release-version }}. This should be the first PR merged during development of version ${{ inputs.new-release-version }}"
          reviewers: yardasol
          milestone: ${{ inputs.milestone-number }}
          labels: |
            Priority:1-Critical
            Status:5-In Review
            Type:Style
            Type:Docs
            Difficulty:1-Beginner
            Comp:Build

