# Preamble
name: Populate SaltProc release notes

on:
  release:
    type: [created, edited, published]
  push:
  #  branches:
  #    - master 
  #  paths:
  #    - 'doc/releasenotes/**'
  # enable worflow to be run manually
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install pandoc and jq 
        run: |
          pip install pandoc
          sudo apt install jq


          # NEED TO FIND A WAY TO ACCESS THE FIRST JSON OBJECT IN THE OUTPUT
      - name: Get most recent release version
        run: RELEASE_VERSION="$(gh api repos/${{ github.repository }}/releases/ | jq '[.0] | .tag_name')""

      - name: Convert .rst to .md 
        run: pandoc -s -o RELEASENOTES.md doc/releasenotes/$RELEASE_VERISON.rst

      - name: Get release data in an environment variable
        run: DESCRIPTION="$(cat RELEASENOTES.md)" 

      - name: Populate the release description with RELEASENOTES.md
        run: |
          gh api repos/${{ github.repository }}/releases/tags/$RELEASE_VERSION \
          -X PATCH -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          -F body="${DESCRIPTION}"


