# Preamble
name: Populate SaltProc release notes

on:
  push:
  #  branches:
  #    - master 
  #  paths:
  #    - 'doc/releasenotes/**'
  # enable worflow to be run manually
  workflow_dispatch:

jobs:
  populate-releasenotes:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

   # - name: Set up conda
   #     uses: conda-incubator/setup-miniconda@v2
   #     with:
   #       miniforge-variant: Mambaforge # mamba is faster than base conda
   #       miniforge-version: latest
   #       activate-environment: saltproc-doc-env
   #       use-mamba: true
   #       use-only-tar-bz2: true
   #   - run: |
   #       conda config --env --set pip_interop_enabled True


      - name: install pandoc 
        run: |
          conda install -c conda-forge pandoc
          pip install --upgrade pandoc

      - name: Get most recent draft release version
        run: |
          echo "RELEASE_VERSION=$(gh api repos/${{ github.repository }}/releases --jq '.[0] | .name')" >> $GITHUB_ENV
          echo "RELEASE_ID=$(gh api repos/${{ github.repository }}/releases --jq '.[0] | .id')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert .rst to .md 
        #if: contains("$(ls doc/releasenotes/v*.rst)", env.RELEASE_VERSION)
        run: pandoc -s -o RELEASENOTES.md -f rst -t gfm doc/releasenotes/${{ env.RELEASE_VERSION }}.rst


      - name: Populate the release description with RELEASENOTES.md
        #if: contains($(ls), 'RELEASENOTES.md')
        run: |
          gh api repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }} \
          -H "Authorize: token ${{ GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -X PATCH \
          -F body="$(cat RELEASENOTES.md)"
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


