# Preamble
name: Populate SaltProc release notes

on:
  release:
    type: [created, edited, published]
  push:
  #  branches:
  #    - master 
  #  paths:
  #    - 'doc/releasenotes/**'
  # enable worflow to be run manually
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install pandoc 
        run: pip install pandoc

      - name: Convert .rst to .md 
        run: pandoc -s -o RELEASENOTES.md doc/releasenodes/{$RELEASE_VERISON}.rst

      - name: Get release data in an environment variable
        run: DESCRIPTION="$(cat RELEASENOTES.md)" 

      - name: Populate the release description with RELEASENOTES.md
        run:
          curl --request PATCH \
          --url https://api.github.com/repos/${{ github.repository }}/releases/tags/v0.4.0 \
        --header 'Accept: application/vnd.github.v3+json' \
        --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{body:${{ DESCRIPTION }}}'

