# Preamble
name: Test download openmc

on:
  push:
  pull_request:
  workflow_run:
    workflows: ["Cache dependencies"]
    types: [completed]
  # enable worflow to be run manually
  workflow_dispatch:

env:
  CACHE_NUMBER: 0 #change to manually reset cache

jobs:
  test-saltproc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    env:
      OPENMC_VERSION: '0.13.0'
      MPI: no
      OMP: no
      PHDF5: no
      DAGMC: no
      EVENT: no
      VECTFIT: no
      LIBMESH: no

    steps:
      - uses: actions/checkout@v2

      - name: Build OpenMC
        run: |
          wget -O - https://codeload.github.com/openmc-dev/openmc/tar.gz/refs/tags/v${{ env.OPENMC_VERSION }} | tar -C $HOME -xz
          CURRENT=$GITHUB_WORKSPACE
          cd $HOME/openmc-${{ env.OPENMC_VERSION }}
          cd $CURRENT
