# Preamble
name: Test SaltProc (pip) 

on:
  push:
    branches:
      - ci-testing

jobs:
  test-saltproc-pip:
    runs-on: ubuntu-latest
    steps:
# Setup python
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

# Check for existing cache
      - name: Find cache location
        id: pip-cache
        run: |
          echo "::set-output name=dir ::$(pip cache dir)"

# Cache packages
      - uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0 # may not be necessary...
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ env.CACHE_NUMBER }}
          restore-keys: |
            ${{ runner.os }}-pip-

# Install saltproc
      - name: Install dependencies and SaltProc
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme
          python setup.py install --user

          # Test saltproc
          pytest --ignore saltproc/test/integration_tests saltproc
