# Preamble
name: Test SaltProc (conda-v-1)

on:
  push:
    branches:
      - ci-testing
  #  schedule:
  #    - cron: '0 9 * * 1' # run every monday @ 9AM

jobs:
  test-saltproc-conda:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        
# Check for existing cache
      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        id: conda-cache
        env:
          CACHE_NUMBER: 2
        with:
          path: /usr/share/miniconda3/envs/saltproc-env
          key: ${{ runner.os }}-conda1-$${ hashFiles('conda-dependencies.yml')-${{ env.DATE }}-${{ env.CACHE_NUMBER }} }
          restore-keys: |
            ${{ runner.os }}-conda1-

# Set up conda
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: saltproc-env
          use-mamba: true
          use-only-tar-bz2: true
      - run: |
          conda config --env --set pip_interop_enabled True

# Install dependencies
      - name: Update environment
        if: steps.conda-cache.outputs.cache-hit != 'true'
        run: mamba env update -n saltproc-env -f environment.yml

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


      - name: Build saltproc
        run: |
          conda activate saltproc-env
          python setup.py install

      - name: Test saltproc
        run: |
          conda activate saltproc-env
          pytest --ignore saltproc/tests/integration_tests saltproc
