# Preamble
name: Test SaltProc

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows: ["Cache Dependencies"]
    types: [completed]

env:
  CACHE_NUMBER: 0 #change to manually reset cache

jobs:
  call-cache-dependencies:
    uses: yardasol/saltproc/.github/workflows/cache-dependencies.yml@ci-testing
    #uses: arfc/saltproc/.github/workflows/cache-dependencies.yml@master

  test-saltproc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Test SaltProc
        run: pytest --ignore saltproc/tests/integration_tests saltproc
